# Generated by Django 4.0.3 on 2022-04-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_remove_image_user_alter_image_caption_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
