# Generated by Django 4.0.3 on 2022-04-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0009_profile_followers_profile_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
