# Generated by Django 4.0.3 on 2022-04-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0011_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
