# Generated by Django 4.0.3 on 2022-07-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0018_like_value_remove_image_likes_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
